name: Revolut CI
on: [push, pull_request]
jobs:
  revolut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Test commit range
        if: github.event_name == 'pull_request'
        env:
          RANGE: ${{ toJSON(github.event.commits.*.id) }}
          SHA: ${{ toJSON(github.event.commits.*.sha) }}
          EVENT: ${{ toJSON(github) }}
        run: |
          echo $RANGE
          echo $SHA
          echo $EVENT
        shell: bash
      - name: Make install
        run: make install
      - name: Testing
        run: make test
      - name: Coverage
        run: codecov

